Title                            = "Danse Val-de-Reuil - Moderne Street Art"
baseURL                          = "https://www.valdereuil-danse.fr/"  # Your domain name. Must end with "/"
theme                            = "introduction"
DefaultContentLanguage           = "fr"                    # Default language for multilingual sites
googleAnalytics                  = "UA-171133850-1"                       # https://gohugo.io/templates/internal/#google-analytics



[params]
    themeStyle                   = "light"                 # Choose "light" or "dark"
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    customCSS                    = ["foo.css"]             # Include custom css files placed under assets/
    
    favicon                      = "/img/favicon.ico"          # Path to favicon file
    email                        = "modernestreet@gmail.com"   # E-mail address for contact section
    description                  = "Cours de danse moderne et street sur Val de Reuil. Modern Street Art association de danse sur la commune de Val De Reuil. La danse dans toutes ses formes (stage, cours, exposition)"   # Max 160 characters show in search results
    footerText                   = "-"                      # Text to override default footer text (markdown allowed)

    # Configure the home page
    [params.home]
        introHeight              = "fullheight"            # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects

        # localTime                = true                    # Show your current local time in contact section
        timeZone                 = "Europe/Paris"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "h:mm A"                # https://momentjs.com/docs/#/displaying/format/
    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
        # twitter                  = true
        facebook                 = true
        instagram                = true
        # googlePlus               = true
        # pinterest                = true

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
        # [[params.social]]
        #     url   = "https://twitter.com/"
        #     icon  = "twitter" # icon name without the 'fa-'
        #     icon_pack = "fab"
    [[params.social]]
        url   = "https://www.facebook.com/modernestreet/"
        # icon  = "facebook-f" # icon name without the 'fa-'
        # icon  = "fa-facebook-official" # icon name without the 'fa-'
        icon  = "facebook-square" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://www.instagram.com/modernestreet/"
        icon  = "instagram" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url = "mailto:modernestreet@gmail.com"  # For a direct email link, use "mailto:test@example.org".
        icon = "paper-plane" # icon name without the 'fa-'
        icon_pack = "fas"



# If you don't want to use the default menu, you can define one by yourself
# [[menu.main]]
#     name    = "Home"
#     url     = "/"
#     weight  = 0
# [[menu.main]]
#     name    = "Blog"
#     url     = "/blog/"
#     weight  = 1

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"

# [languages]
#     [languages.fr]
#         languageName     = "Français"
#         languageCode     = "fr"
#         contentDir       = "content/fr"
#         weight           = 0
#         title            = "Introduction"
#         [languages.fr.params]
#             description  = "Website Description"   # Max 160 characters show in search results
#             footerText   = "Moderne Street Art est une association de danse sur la commune de Val De Reuil qui a pour but de promouvoir la danse dans toutes ses formes (stage, cours, exposition)."                      # Text to override default footer text (markdown allowed)

# [languages]
#     [languages.en]
#         languageName     = "English"
#         languageCode     = "en-us"
#         contentDir       = "content/en"
#         weight           = 0
#         title            = "Introduction"
#         [languages.en.params]
#             description  = "Website Description"   # Max 160 characters show in search results
#             # footerText   = ""                      # Text to override default footer text (markdown allowed)

    # [languages.es]
    #     languageName     = "Español"
    #     languageCode     = "es"
    #     contentDir       = "content/es"
    #     weight           = 1
    #     title            = "Introducción"
    #     [languages.es.params]
    #         description  = "Descripcion del sitio web"
    #         # footerText   = ""

  